service: rvm-odoo-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  # =========================
  # REST API (v1)
  # =========================
  apiGateway:
    shouldStartNameWithService: true

    # ðŸ”’ RATE LIMIT REAL
    throttling:
      rateLimit: 2        # requests por segundo
      burstLimit: 5       # picos permitidos

  environment:
    ODOO_URL: ${param:odoo_url}
    ODOO_DB: ${param:odoo_db}
    ODOO_USER: ${param:odoo_user}
    ODOO_PASSWORD: ${param:odoo_password}

package:
  patterns:
    - '!.env'
    - '!.env.*'
    - '!frontend/**'
    - '!.git/**'
    - '!README.md'
    - '!node_modules/**'

functions:
  createLead:
    handler: src/handler.createLead
    events:
      - http:
          path: leads
          method: post
          cors:
            origins:
              - https://realvaluemarketing.com
              - https://www.realvaluemarketing.com
              - http://localhost:5173
            headers:
              - Content-Type
