service: rvm-odoo-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

  httpApi:
    cors:
      allowedOrigins:
        - https://realvaluemarketing.com
        - https://www.realvaluemarketing.com
        - http://localhost:5173
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - POST
        - OPTIONS

  environment:
    ODOO_URL: ${env:ODOO_URL}
    ODOO_DB: ${env:ODOO_DB}
    ODOO_USER: ${env:ODOO_USER}
    ODOO_PASSWORD: ${env:ODOO_PASSWORD}

functions:
  createLead:
    handler: src/handler.createLead
    events:
      - httpApi:
          path: /leads
          method: POST
